-- ScraperFC initial schema
-- Generated from app/models/*.py

create table if not exists public.sports (
    id integer generated by default as identity primary key,
    key varchar(50) not null unique,
    name varchar(100) not null,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create index if not exists ix_sports_key on public.sports (key);

create table if not exists public.leagues (
    id integer generated by default as identity primary key,
    sport_id integer not null references public.sports(id),
    name varchar(200) not null,
    country varchar(100),
    canonical_name varchar(200) not null,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    constraint uq_league_sport_canonical unique (sport_id, canonical_name)
);

create index if not exists ix_leagues_sport_canonical on public.leagues (sport_id, canonical_name);
create index if not exists ix_leagues_country on public.leagues (country);

create table if not exists public.teams (
    id integer generated by default as identity primary key,
    sport_id integer not null references public.sports(id),
    name varchar(200) not null,
    canonical_name varchar(200) not null,
    country varchar(100),
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    constraint uq_team_sport_canonical unique (sport_id, canonical_name)
);

create index if not exists ix_teams_sport_canonical on public.teams (sport_id, canonical_name);

create table if not exists public.matches (
    id integer generated by default as identity primary key,
    sport_id integer not null references public.sports(id),
    league_id integer not null references public.leagues(id),
    season varchar(50),
    home_team_id integer not null references public.teams(id),
    away_team_id integer not null references public.teams(id),
    match_datetime_utc timestamp not null,
    status varchar(50) not null,
    home_score integer,
    away_score integer,
    source_primary varchar(50) not null,
    source_external_id varchar(100),
    last_synced_at timestamp not null default now(),
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    constraint uq_match_unique_game unique (league_id, home_team_id, away_team_id, match_datetime_utc)
);

create index if not exists ix_matches_datetime on public.matches (match_datetime_utc);
create index if not exists ix_matches_status on public.matches (status);
create index if not exists ix_matches_league on public.matches (league_id);
create index if not exists ix_matches_home_team on public.matches (home_team_id);
create index if not exists ix_matches_away_team on public.matches (away_team_id);
create index if not exists ix_matches_source on public.matches (source_primary, source_external_id);

create table if not exists public.external_mappings (
    id integer generated by default as identity primary key,
    entity_type varchar(50) not null,
    entity_id integer not null,
    source varchar(50) not null,
    external_id varchar(200) not null,
    created_at timestamp not null default now(),
    league_id integer references public.leagues(id),
    team_id integer references public.teams(id),
    constraint uq_external_mapping unique (entity_type, source, external_id)
);

create index if not exists ix_external_entity on public.external_mappings (entity_type, entity_id);
create index if not exists ix_external_source on public.external_mappings (source, external_id);

create table if not exists public.sync_runs (
    id integer generated by default as identity primary key,
    started_at timestamp not null,
    finished_at timestamp,
    status varchar(50) not null,
    source varchar(50),
    matches_created integer default 0,
    matches_updated integer default 0,
    error_message text,
    created_at timestamp not null default now()
);

create index if not exists ix_sync_runs_started on public.sync_runs (started_at);
create index if not exists ix_sync_runs_status on public.sync_runs (status);
